_BASE_: "../Base-RCNN-DilatedC5.yaml"
DATASETS:
  TRAIN: ('coco_2014_train', 'coco_2014_valminusminival')
  PROPOSAL_FILES_TRAIN: ('datasets/proposals/coco_2014_train_mcg_proposals_d2.pkl', 'datasets/proposals/coco_2014_valminusminival_mcg_proposals_d2.pkl')
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 4000
  TEST: ('coco_2014_minival',)
  PROPOSAL_FILES_TEST: ('datasets/proposals/coco_2014_minival_mcg_proposals_d2.pkl',)
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 4000
