DATALOADER:
  NUM_WORKERS: 0
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNWS"
  RPN:
    IN_FEATURES: ["res5"]
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 4096
    POSITIVE_FRACTION: 1.0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
VERSION: 2
