_BASE_: "../Base-RCNN-DilatedC5.yaml"
DATASETS:
  TRAIN: ('voc_2012_trainval',)
  PROPOSAL_FILES_TRAIN: ('datasets/proposals/voc_2012_trainval_mcg_proposals_d2.pkl',)
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 4000
  TEST: ('voc_2007_test',)
  PROPOSAL_FILES_TEST: ('datasets/proposals/voc_2007_test_mcg_proposals_d2.pkl',)
  #TEST: ('voc_2012_test')
  #PROPOSAL_FILES_TEST: ('datasets/proposals/voc_2012_test_mcg_proposals_d2.pkl')
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 4000
